CREATE TABLE employees
(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    firstName VARCHAR(255) DEFAULT NULL,
	middleName VARCHAR(255) DEFAULT NULL,
	lastName VARCHAR(255) DEFAULT NULL,
	age INTEGER DEFAULT NULL,
    salary DOUBLE DEFAULT NULL,
	createdBy VARCHAR(255) DEFAULT NULL,
	createdTs TIMESTAMP DEFAULT NULL,
	updatedBy VARCHAR(255) DEFAULT NULL,
	updatedTs TIMESTAMP DEFAULT NULL,
	active TINYINT DEFAULT 0
);